### ISSUE TITLE
Question: Exodus Privacy for Desktop Apps?

### ISSUE THREAD

**Issue by FrostBlade5** [Exodus-Privacy/website#145]
First of this is not an issue but a question.
Big THANK YOU for creating Exodus Privacy, you are the best!

I noticed that the mobile app version of for example Discord includes facebook login and google analytics.
Wiped my phone and did not install a single app with trackers or suspicious permissions.

Do you offer a service or are you aware of any service which allows me to identify trackers for the Discord Desktop PC App?
Not only Discord but generally, a website/service that shows me if a desktop program has trackers in it, that would be MUCH NEEDED. I am afraid whenever i use Discord on my PC, it connects to facebook...
In that case i would have to wipe my PC and not use Discord ever again.

Thank you for helping.

**Comment by FrostBlade5** [comment]
Anyone?

**Comment by codeurimpulsif** [comment]
Hi, the purpose of the Exodus platform is to scan Android applications, not other system programs, network analysis can be performed on this devices for example.

**Comment by FrostBlade5** [comment]
No possibility to scan desktop pc programs/applications?
Doesn't have to be exodus privacy but any option would be welcome for privacy..

**Comment by FrostBlade5** [comment]
I was truely hoping to find a source to scan desktop apps for trackers.

**Comment by mpeter50** [comment]
I'm **not** an Exodus team member, but I may be able to give you some information.

Exodus probably won't be able to do that (in the foreseeable future), because of a few reasons.

First, their service has been built for scanning Android apps, and probably they would need to change large parts of it to support other platforms. This is probably not hard to do, but still a lot of work.

Secondly, scanning Android apps is easy because they are written in Java, and scanning/reverse engineering code written for a Java vm is much easier than it is with most other languages. This is because in Java the structure and identifiers of the code is usually much better preserved after compilation compared to other languages. You can read more [here](https://exodus-privacy.eu.org/en/post/exodus_static_analysis/).
For desktop apps, the discord client may not be _that_ hard actually, as it is basically built on chromium and with javascript, but most other software is much harder to analyse.
This actually also affects Android apps: those apps that are not written in Java, or at least have non-java components, Exodus cannot scan them in full.

The thing is, all of this (what Exodus does) would be the job of antivirus software, which are made by companies with much more resources for research.
A decade earlier the term "spyware" was known as software that uploads your private information without your direct permission, but today it is just natural that it is embedded in most popular software.
Clearly it seems, though, that antivirus makers don't want to warn people about spyware on their computers.
Exodus does the job of antivirus software (specifically the detection part, not notifying or removing) for Android apps, as best as they can with their resources.

**Comment by NolonQ** [comment]
> I'm **not** an Exodus team member, but I may be able to give you some information.
> 
> Exodus probably won't be able to do that (in the foreseeable future), because of a few reasons.
> 
> First, their service has been built for scanning Android apps, and probably they would need to change large parts of it to support other platforms. This is probably not hard to do, but still a lot of work.
> 
> Secondly, scanning Android apps is easy because they are written in Java, and scanning/reverse engineering code written for a Java vm is much easier than it is with most other languages. This is because in Java the structure and identifiers of the code is usually much better preserved after compilation compared to other languages. You can read more [here](https://exodus-privacy.eu.org/en/post/exodus_static_analysis/). For desktop apps, the discord client may not be _that_ hard actually, as it is basically built on chromium and with javascript, but most other software is much harder to analyse. This actually also affects Android apps: those apps that are not written in Java, or at least have non-java components, Exodus cannot scan them in full.
> 
> The thing is, all of this (what Exodus does) would be the job of antivirus software, which are made by companies with much more resources for research. A decade earlier the term "spyware" was known as software that uploads your private information without your direct permission, but today it is just natural that it is embedded in most popular software. Clearly it seems, though, that antivirus makers don't want to warn people about spyware on their computers. Exodus does the job of antivirus software (specifically the detection part, not notifying or removing) for Android apps, as best as they can with their resources.

I'm late to the party but have a question.
Are there any opensource android firewall apps? On PC there are some options to monitor network traffic, my favorite is portmaster from safing.io
On mobile however i sadly found nothing except AF-Wall which does it's job but has two downsides in my opinion.
It requires ROOT and it conflicts with VPN useage.
The portmaster might come to android aswell, however they need more donations for that.. so while waiting for that what's out there now that we can use on android?

**Comment by mpeter50** [comment]
There is [NetGuard](https://f-droid.org/en/packages/eu.faircode.netguard/) but technically that too works as a VPN, and I don't know of a way for chaining VPN clients.

However, are you sure that AFWall conflicts with VPN usage when it has root permissions?
I think this should be possible to be done **with** root permissions, but without that, the only option for an app is to present itself as a VPN client, as thats how they will receive all traffic.

**Comment by codeurimpulsif** [comment]
I'm closing this issue because people have responded and it's not exodus related.
