### ISSUE TITLE
Docs: help installing Hugo's needed specific version

### ISSUE THREAD

**Issue by dimitri-bourreau** [Exodus-Privacy/website#156]
## What could be improved

Currently, `README.md` recommends to install a specific range of versions of `hugo`:

https://github.com/Exodus-Privacy/website/blob/96d00e3c06201ae6c23a4dda75d56cb289204147/README.md?plain=1#L15

It doesn't give advices on it.

## Why it coult be improved

When contributing, installing `hugo` must be done without friction, allowing everyone to help out easily.

## Install hugo v.0.54.0

I am myself a developer, and I am struggling with this on Mac. 

`brew install hugo@0.54.0` and `brew install hugo@0.54` are failing with `No available formula with the name "hugo@..."`.

The `hugo` official docs does not give specifics.

For now, it seems building from source is the easiest way.

- [hugo docs for building from source](https://gohugo.io/getting-started/installing#build-from-source-on-mac)
- [v.0.54.0 release on GitHub](https://github.com/gohugoio/hugo/releases/tag/v0.54.0)

What do you think?

Is there an easy way to install a specific version of `hugo`?

**Comment by pnu-s** [comment]
Hi @dimitri-bourreau and thanks for opening this issue!

That's an interesting question.

Although I understand the problem here, I personally do not think that this is our responsibility to provide (and maintain!) information about how to download a specific version of Hugo, but rather to provide a link to hugo official docs which say how to do that.

If that official documentation does not exist, that's more problematic. One possible way could be to open a similar issue on their repository. 

If I recall correctly, what I did personally was to download the binary from the release on GitHub.

**Comment by dimitri-bourreau** [comment]
Hi,

It makes sense, thanks. 👍
I'll close this issue then.
